<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6rQPy9F\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6rQPy9F/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6rQPy9F.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6rQPy9F\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container6rQPy9F\srcDevDebugProjectContainer(array(
    'container.build_hash' => '6rQPy9F',
    'container.build_id' => '142b1efe',
    'container.build_time' => 1519253176,
));
